### ISSUE TITLE
项目需要python脚本

### ISSUE THREAD

**Issue by jihe520** [LaoDie1/Godot-FunASR-UI#1]
![image](https://github.com/LaoDie1/Godot-FunASR-UI/assets/36144612/4d70d0bf-58bf-4b51-ba54-0123ae440604)
这个脚本能同步上传嘛，大佬

**Comment by LaoDie1** [comment]
下载这个压缩包
```
wget https://isv-data.oss-cn-hangzhou.aliyuncs.com/ics/MaaS/ASR/sample/funasr_samples.tar.gz
```
内容查看文章：https://blog.csdn.net/qq_37280924/article/details/138170217

![image](https://github.com/LaoDie1/Godot-FunASR-UI/assets/34774872/9f4d0251-0c0b-4650-98ec-f9f32709889f)

在是里面的的 funasr_wss_client.py 文件，搜索一下就找到了
